Repository facn5/GeekWars, pull requests merged in 2019-04, with the labels that each got.

#21 Sqlqueries
  database/queries/queries.js
  database/queries/sqlquery.js
  tests/backend_test.js
Labels: Back-end

#25 Sign
  public/index.html
  public/login.html
  public/sign.css
  src/handlers.js
  src/router.js
Labels: Front-end

#44 Getquestions
  database/db_build.sql
  public/main.html
  public/scripts/fetch.js
  public/scripts/getdata.js
  public/scripts/login.js
  public/style/main.css
  src/handlers.js
  src/router.js
Labels: Back-end, Done, SQL, database

#47 Logincookies
  package-lock.json
  package.json
  public/scripts/login.js
  src/handlers.js
  src/server.js
Labels: Back-end, Done, Front-end, enhancement

#53 Signup
  public/login.html
  public/sign_up.html
  public/style/sign_up.css
Labels: Done, Front-end

#55 Score
  database/queries/queries.js
  public/main.html
  public/scripts/getdata.js
  public/scripts/getscore.js
  src/handlers.js
  src/router.js
  src/server.js
Labels: Back-end, Front-end, SQL
